FROM williamyeh/ansible:ubuntu14.04

WORKDIR /tmp
COPY  .  /tmp/ansible-vim

RUN echo 127.0.0.1 > inventory

RUN ansible-playbook -i inventory ansible-vim/tests/provision.yml --connection=local --sudo
